# Generated by Django 3.0.3 on 2020-03-03 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20200303_0904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='is_true',
            new_name='is_correct',
        ),
    ]
