# Generated by Django 3.0.3 on 2020-03-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_currentquiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentquiz',
            name='questions_passed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='currentquiz',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
    ]
