# Generated by Django 3.0.3 on 2020-03-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20200303_0942'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='second_name',
        ),
        migrations.AlterField(
            model_name='profile',
            name='quiz',
            field=models.ManyToManyField(blank=True, related_name='users', to='management.Quiz'),
        ),
    ]
